#!/usr/bin/env bash

set -e

git -C "dotbot" submodule sync --quiet --recursive
git submodule update --init --recursive "dotbot"

case "$1" in
  all)
    dotbot/bin/dotbot -d . -c configs/git-repositories.conf.yaml -p dotbot-git/git.py
    dotbot/bin/dotbot -d . -c configs/yay-packages.conf.yaml -p dotbot-yay/yay.py
    dotbot/bin/dotbot -d . -c configs/links.conf.yaml
    ;;
  *)
    dotbot/bin/dotbot -d . -c "$1" -p dotbot-git/git.py -p dotbot-yay/yay.py
esac
