# Apply to all commands that come after setting the defaults
- defaults:
    link:
        create: true # Create parent directories to the link as needed
        relink: true # Removes the old target if it's a symlink

# Remove dead symbolic links
- clean: ['~']

# Apps
- link:
    ~/.bash_profile: apps/bash/bash_profile
    ~/.bashrc: apps/bash/bashrc

- link:
    ~/.gitconfig: apps/git/gitconfig

- link:
    ~/.inputrc: apps/readline/inputrc

- link:
    ~/.bundle/config: apps/ruby/bundle/config
    ~/.gemrc: apps/ruby/gemrc

- link:
    ~/.cargo/config: apps/rust/cargo/config

- link:
    ~/.vimrc: apps/vim/vimrc
    ~/.vim/autoload/plug.vim: apps/vim/autoload/plug.vim
- shell:
    - [vim -c 'PlugInstall' +qall, Installing vim plugins]

- link:
    ~/.xprofile: apps/x11/xprofile
    ~/.Xresources: apps/x11/Xresources
